/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ../com.deepin.dbus.usrdata.xml -i widget.h -a widgetAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "widgetAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class UsrdataAdaptor
 */

UsrdataAdaptor::UsrdataAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

UsrdataAdaptor::~UsrdataAdaptor()
{
    // destructor
}

int UsrdataAdaptor::ReceiveUsrData(const QString &name, int age, const QString &phone, const QString &id, const QString &address, double temp)
{
    // handle method call com.deepin.dbus.usrdata.ReceiveUsrData
    int out0;
    QMetaObject::invokeMethod(parent(), "ReceiveUsrData", Q_RETURN_ARG(int, out0), Q_ARG(QString, name), Q_ARG(int, age), Q_ARG(QString, phone), Q_ARG(QString, id), Q_ARG(QString, address), Q_ARG(double, temp));
    return out0;
}

