/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ../com.deepin.dbus.usrdata.xml -i widget.h -a widgetAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef WIDGETADAPTOR_H
#define WIDGETADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "widget.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.dbus.usrdata
 */
class UsrdataAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.dbus.usrdata")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.dbus.usrdata\">\n"
"    <method name=\"ReceiveUsrData\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"age\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"phone\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"id\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"address\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"temp\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    UsrdataAdaptor(QObject *parent);
    virtual ~UsrdataAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int ReceiveUsrData(const QString &name, int age, const QString &phone, const QString &id, const QString &address, double temp);
Q_SIGNALS: // SIGNALS
};

#endif
